### ISSUE TITLE
Hive Metastore: Import fails with "KeyError: 'Database Name'" in DBR 10.4

### ISSUE THREAD

**Issue by ravirahul-db** [databrickslabs/migrate#164] opened 2022-04-19 13:25 UTC
At https://github.com/databrickslabs/migrate/blob/master/dbclient/HiveClient.py#L179 we are performing an operation on key `Database Name`, but in DBR 10.4 this is being exported as `Namespace Name` and failing during import with below error.

```
ravirahul.padmanabhan@C02FM2K9MD6M migrate-master % python import_db.py --profile az --azure --metastore --cluster-name "master_10.4" --set-export-dir ./metastore
Importing the metastore configs at 2022-04-19 18:35:35.452451
Get: https://adb-8596220602934265.5.azuredatabricks.net/api/2.0/clusters/list
Starting master_10.4 with id 0419-130137-ylvb077y
post: https://adb-8596220602934265.5.azuredatabricks.net/api/2.0/clusters/start
2022-04-19,18:35:36;WARNING;{"error_code": "INVALID_STATE", "message": "Cluster 0419-130137-ylvb077y is in unexpected state Running."}

2022-04-19,18:35:36;ERROR;Cluster 0419-130137-ylvb077y is in unexpected state Running.
Get: https://adb-8596220602934265.5.azuredatabricks.net/api/2.0/clusters/get
2022-04-19,18:35:39;INFO;Creating remote Spark Session
post: https://adb-8596220602934265.5.azuredatabricks.net/api/1.2/contexts/create
post: https://adb-8596220602934265.5.azuredatabricks.net/api/2.0/dbfs/mkdirs
Traceback (most recent call last):
  File "/Users/ravirahul.padmanabhan/Desktop/hive/migrate-master/import_db.py", line 275, in <module>
    main()
  File "/Users/ravirahul.padmanabhan/Desktop/hive/migrate-master/import_db.py", line 128, in main
    hive_c.import_hive_metastore(cluster_name=args.cluster_name, has_unicode=args.metastore_unicode,
  File "/Users/ravirahul.padmanabhan/Desktop/hive/migrate-master/dbclient/HiveClient.py", line 364, in import_hive_metastore
    all_db_details_json = self.get_database_detail_dict()
  File "/Users/ravirahul.padmanabhan/Desktop/hive/migrate-master/dbclient/HiveClient.py", line 179, in get_database_detail_dict
    db_name = db_json.pop('Database Name')
KeyError: 'Database Name'
```

**DBR 9.1 LTS:**
```{"Database Name": "default", "Comment": "Default Hive database", "Location": "dbfs:/user/hive/warehouse", "Owner": "public", "Properties": ""}```

**DBR 10.4 LTS:**
```{"Namespace Name": "default", "Comment": "Default Hive database", "Location": "dbfs:/user/hive/warehouse", "Owner": "public", "Properties": ""}```

**Comment by mrchristine** [comment] 2022-04-19 14:58
Thanks. I'm asking our eng team to look into this.

**Comment by ravirahul-db** [comment] 2022-04-23 10:23
@mrchristine I have used the same DBR 10.4 LTS to export and import. I guess the DBR 10.4 will be able to process `Namespace Name`, but fails at import due to migrate tool looking for only `Database Name`.

Data as part of migration: New workspace which has only a single table.
```
%sql
CREATE TABLE default.people10m OPTIONS (
  PATH 'dbfs:/databricks-datasets/learning-spark-v2/people/people-10m.delta'
)
``` 

Commands executed:
```
python export_db.py --profile az --azure --metastore --cluster-name "master_10.4" --set-export-dir ./metastore
python import_db.py --profile az --azure --metastore --cluster-name "master_10.4" --set-export-dir ./metastore
```

Cluster config:
```
{
    "autoscale": {
        "min_workers": 1,
        "max_workers": 8
    },
    "cluster_name": "master_10.4",
    "spark_version": "10.4.x-scala2.12",
    "spark_conf": {
        "spark.databricks.delta.preview.enabled": "true"
    },
    "azure_attributes": {
        "first_on_demand": 1,
        "availability": "SPOT_WITH_FALLBACK_AZURE",
        "spot_bid_max_price": -1
    },
    "node_type_id": "Standard_DS3_v2",
    "driver_node_type_id": "Standard_DS3_v2",
    "ssh_public_keys": [],
    "custom_tags": {},
    "spark_env_vars": {},
    "autotermination_minutes": 120,
    "enable_elastic_disk": true,
    "cluster_source": "UI",
    "init_scripts": [
        {
            "dbfs": {
                "destination": "dbfs:/databricks/init_scripts/set_exec_context_limit.sh"
            }
        }
    ],
    "cluster_id": "0420-121836-mi23ap3b"
}
```

**Comment by mrchristine** [comment] 2022-04-25 14:10
I cannot reproduce this and you might have lingering logs in your local machine. Please clear you logs and try again. Use the `--reset-exports` command first, then try to export/import using the same DBR version. 
If you can reproduce this, we can re-open for investigation.

**Comment by laurence-wells** [comment] 2022-05-30 10:54
Hi All, 

Just to confirm we have replicated this issue when updating to 10.4

`  
File "/home/vsts/work/1/s/import_db.py", line 276, in <module>
    main()
  File "/home/vsts/work/1/s/import_db.py", line 129, in main
    hive_c.import_hive_metastore(cluster_name=args.cluster_name, has_unicode=args.metastore_unicode,
  File "/home/vsts/work/1/s/dbclient/HiveClient.py", line 364, in import_hive_metastore
    all_db_details_json = self.get_database_detail_dict()
  File "/home/vsts/work/1/s/dbclient/HiveClient.py", line 179, in get_database_detail_dict
    db_name = db_json.pop('Database Name')
KeyError: 'Database Name'
##[error]The process '/opt/hostedtoolcache/Python/3.10.4/x64/bin/python' failed with exit code 1
`

**Comment by laurence-wells** [comment] 2022-05-30 14:42
> @laurence-wells please see my comment above. Reset your export directory and make sure you use the same DBR version during export and import. There's a keyspace difference between runtime versions that cause this issue.
> 
> If it continues to fail, provide exact steps on how to reproduce it so we can triage it further.

I would be surprised as we are running this through devops it spins up and destroys the box each time (so in effect its a brand new box every time) 

I have attached the YAML and config for the cluster 

`
schedules:
\- cron: 0 1 * * *
  branches:
    include:
    \- refs/heads/master
  always: true
jobs:
\- job: Job_2
  displayName: MetastoreMigration
  pool:
    vmImage: ubuntu-latest
  steps:
  \- checkout: self
 
  \- task: UsePythonVersion@0
    displayName: Use Python 3.x
  \- task: PythonScript@0
    displayName: Install Dependencies
    inputs:
      scriptPath: setup.py
      arguments: install
  \- task: configuredatabricks@0
    displayName: Configure Databricks CLI
    inputs:
      url: $(workspace-url)
      token: ----
  \- task: PythonScript@0
    displayName: Export metastore
    inputs:
      scriptPath: export_db.py
      arguments: --metastore --profile AZDO --debug --azure
  \- task: configuredatabricks@0
    displayName: Configure Databricks CLI DR
    inputs:
      url: $(secondary-workspace-url)
      token: ----
  \- task: PythonScript@0
    displayName: Import Metastore
    inputs:
      scriptPath: import_db.py
      arguments: --metastore --profile AZDO --debug --azure
  \- task: PythonScript@0
    displayName: Import RepairLog
    inputs:
      scriptPath: import_db.py
      arguments: ' --profile AZDO --debug --azure --get-repair-log '
`

Config: 
`
{
    "num_workers": 0,
    "cluster_name": "API_Metastore_Work_Leave_Me_Alone",
    "spark_version": "10.4.x-scala2.12",
    "spark_conf": {
        "spark.databricks.cluster.profile": "singleNode",
        "spark.master": "local[*]"
    },
    "node_type_id": "Standard_DS3_v2",
    "ssh_public_keys": [],
    "custom_tags": {
        "ResourceClass": "SingleNode"
    },
    "spark_env_vars": {
        "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
    },
    "autotermination_minutes": 15,
    "init_scripts": []
}
`

**Comment by mrchristine** [comment] 2022-05-31 15:36
I am able to reproduce this issue, I'm re-opening this issue.

**Comment by mrchristine** [comment] 2022-05-31 16:45
@laurence-wells thanks for reporting this, I pushed a fix to the master branch. Please re-test and let me know if you see issues. You shouldn't need to export again, just try re-importing and it should work.

**Closed by mrchristine** 2022-05-31 16:45 UTC

**Comment by laurence-wells** [comment] 2022-06-01 07:54
> 

Thanks @mrchristine tested and can confirm this fixed it for me
