### ISSUE TITLE
Namespace Error

### ISSUE THREAD

**Issue by laurencewells** [databrickslabs/migrate#26] opened 2021-03-15 16:46 UTC
Hi, we had an azure dev-ops pipeline working fine and recently our migration pipeline is failing with the following error on exporting metadata. It is using cluster with the 7.3 LTS runtime. The pipeline has worked successfully before and also works using the templated cluster

Azure Dev-ops error:

 ERROR: 
 <span class="ansi-red-fg">AttributeError</span>: namespace
 {"resultType": "error", "summary": "<span class=\"ansi-red-fg\">AttributeError</span>: namespace", "cause": "---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n/databricks/spark/python/pyspark/sql/types.py in __getattr__(self, item)\n   1594             # but this will not be used in normal cases\n-> 1595             idx = self.__fields__.index(item)\n   1596             return self[idx]\n\nValueError: 'namespace' is not in list\n\nDuring handling of the above exception, another exception occurred:\n\nAttributeError                            Traceback (most recent call last)\n<command--1> in <module>\n----> 1 all_dbs = [x.namespace for x in spark.sql(\"show databases\").collect()]; print(len(all_dbs))\n\n<command--1> in <listcomp>(.0)\n----> 1 all_dbs = [x.namespace for x in spark.sql(\"show databases\").collect()]; print(len(all_dbs))\n\n/databricks/spark/python/pyspark/sql/types.py in __getattr__(self, item)\n   1598             raise AttributeError(item)\n   1599         except ValueError:\n-> 1600             raise AttributeError(item)\n   1601 \n   1602     def __setattr__(self, key, value):\n\nAttributeError: namespace"}
2021-03-15T16:33:09.1574639Z 

----------------------------- Driver Log ---------------------------------------------

ValueError                                Traceback (most recent call last)
/databricks/spark/python/pyspark/sql/types.py in __getattr__(self, item)
   1594             # but this will not be used in normal cases
-> 1595             idx = self.__fields__.index(item)
   1596             return self[idx]

ValueError: 'namespace' is not in list

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<command--1> in <module>
----> 1 all_dbs = [x.namespace for x in spark.sql("show databases").collect()]; print(len(all_dbs))

<command--1> in <listcomp>(.0)
----> 1 all_dbs = [x.namespace for x in spark.sql("show databases").collect()]; print(len(all_dbs))

/databricks/spark/python/pyspark/sql/types.py in __getattr__(self, item)
   1598             raise AttributeError(item)
   1599         except ValueError:
-> 1600             raise AttributeError(item)
   1601 
   1602     def __setattr__(self, key, value):

AttributeError: namespace

**Comment by mrchristine** [comment] 2021-03-15 17:01
Hi @laurencewells . Thanks for reporting this. 
I committed a fix for this 5 days ago `dc891cf202668cc60e21c8edd9d97449468be2f5`. If you can pull the latest changes, it should be resolved. 
The reason was the original Spark 3.0 added a regression to how database attributes were defined, but we fixed that in the latest DBR releases which caused this issue. Please ensure the cluster being used by this tool is restarted and using the latest DBR changes. 
Please let me know if you run into any other issues with the latest changes.

**Comment by laurencewells** [comment] 2021-03-15 17:23
Thanks @mrchristine. This worked. Thanks for your help

**Closed** 2021-03-15 17:23 UTC
